### ISSUE TITLE
Question: mono api exports not available, what can i do ?

### ISSUE THREAD

**Issue by hduarte** [freehuntx/frida-mono-api#3]
In an iOS app, build with xamarin ios, the mono api exports are not available. They are present (found by comparing the assembly code with another ios app) but they are not exported so frida is not able to find them. Is there a way to be able to attach to the mono runtime from frida without this ? Do you know ay way to decompile and/or patch arm aotdata files ?

Please let me now if there is a better place for this type of interaction. Thks.

**Comment by freehuntx** [comment]
Hey, if the api exports are not available you probably have to do some own work.
For example create Pattern for the functions you need.
But thats alot of work i guess.
I will close this issue, since it would be too much extra work.
